/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 账号密码登录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        username: string;
                        /** Format: password */
                        password: string;
                    };
                };
            };
            responses: {
                200: components["responses"]["Token"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登出 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 刷新 token（匿名，凭 refresh token） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshReq"];
                };
            };
            responses: {
                200: components["responses"]["Token"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/external/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前认证提供方配置（前端据此渲染登录入口） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResult"] & {
                            data?: {
                                /** @enum {string} */
                                provider?: "LOCAL" | "OIDC" | "WECHAT";
                                corpId?: string | null;
                                agentId?: string | null;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/external/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDC 回调（Spring Security 接管，浏览器整页跳转，非 XHR） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 重定向回前端（成功/失败） */
                302: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/wechat/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 企微回调（Controller + WechatIdentityAdapter；前端 XHR 直达） */
        get: {
            parameters: {
                query: {
                    code: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Token"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 用户列表（人员选择器；手机号脱敏） */
        get: {
            parameters: {
                query?: {
                    deptId?: number;
                    keyword?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["UserPage"];
            };
        };
        put?: never;
        /** 新增用户（ADMIN） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserCreateReq"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResult"] & {
                            data?: components["schemas"]["UserVO"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 修改密码（首登 must_change_password 引导） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PasswordUpdateReq"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 更新用户（ADMIN） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserUpdateReq"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        post?: never;
        /** 禁用/删除用户（ADMIN） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 部门树 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResult"] & {
                            data?: components["schemas"]["Department"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 新增部门（ADMIN） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeptCreateReq"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 修改部门（含 `leaderId`，ADMIN） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DeptUpdateReq"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        post?: never;
        /** 删除部门（有子级/有成员则拒绝，ADMIN） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手动同步（PULL 模式，ADMIN） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 同步状态（ADMIN） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResult"] & {
                            data?: components["schemas"]["SyncStatus"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 私有 IDM 推送（独立 SecurityFilterChain 校验 Bearer ORGSYNC_PUSH_TOKEN）
         * @description 被动接收私有 IDM（竹云等）的组织/用户推送并 upsert（幂等，以外部源 id 映射；不删实体，仅将移除者置 DISABLED）。 下方为**规范通用报文**；具体厂商私有格式由 `OrgPushAdapter` 解析映射（`02 §3.3`）。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OrgPushPayload"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scim/v2/Users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SCIM 查询用户（`app.orgsync.mode=SCIM`；独立 SecurityFilterChain 校验 Bearer ORGSYNC_PUSH_TOKEN，ADR-008） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        /** SCIM 替换用户（SCIM 模式） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ScimResource"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        /** SCIM 创建用户（SCIM 模式） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ScimResource"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        /** SCIM 删除用户（SCIM 模式） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        options?: never;
        head?: never;
        /** SCIM 局部更新用户（SCIM 模式） */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ScimPatchOp"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        trace?: never;
    };
    "/scim/v2/Groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SCIM 查询部门（SCIM 模式；Group 按名称映射为 sys_department，02 §3.3） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        /** SCIM 替换部门（SCIM 模式） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ScimResource"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        /** SCIM 创建部门（SCIM 模式） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ScimResource"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        /** SCIM 删除部门（SCIM 模式） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        options?: never;
        head?: never;
        /** SCIM 局部更新部门（SCIM 模式） */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ScimPatchOp"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        trace?: never;
    };
    "/jobs/{name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手动重跑调度任务（ADMIN；`sys_job_log` 记录，0306/Q6） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务列表（六大视图） */
        get: {
            parameters: {
                query: {
                    scope: components["schemas"]["Scope"];
                    /** @description 匹配 title/content（大小写不敏感子串） */
                    keyword?: string;
                    /** @description 仅 scope=all 生效；主管筛选其（含递归子部门）下属相关任务，只读（ADR-012） */
                    subordinate?: boolean;
                    date?: string;
                    /** @description 按分类过滤（含子树，ADR-015 共享分类） */
                    categoryId?: number;
                    /** @description 按自定义栏条目过滤（仅本人栏） */
                    menuId?: number;
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["TaskPage"];
            };
        };
        put?: never;
        /** 新建主任务 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskCreateReq"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 各视图计数（recurring 按展开实例） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResult"] & {
                            data?: components["schemas"]["CountVO"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 日历区间（有任务日期/实例） */
        get: {
            parameters: {
                query: {
                    start: string;
                    end: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["TaskList"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/subtasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 子任务列表 */
        get: {
            parameters: {
                query: {
                    parentId: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["TaskList"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResult"] & {
                            data?: components["schemas"]["TaskDetailVO"];
                        };
                    };
                };
            };
        };
        /** 更新任务（须携带 `version`） */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskUpdateReq"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        post?: never;
        /** 软删除（不可逆：清空关联数据；见 R5） */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 完成任务（周期任务可传 dueAt 指定实例，见 R2；更新须携带 version） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskCompleteReq"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/uncomplete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 取消完成（周期任务可传 dueAt；更新须携带 version） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TaskCompleteReq"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/collect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 收藏 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        /** 取消收藏 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的标签 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResult"] & {
                            data?: components["schemas"]["TagVO"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 新增标签 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TagReq"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 改标签 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TagReq"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        post?: never;
        /** 删标签 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 可见分类树（个人 + 部门 + 组织） */
        get: {
            parameters: {
                query?: {
                    /** @description 可选过滤共享范围 */
                    scope?: "PERSONAL" | "DEPARTMENT" | "ORG";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResult"] & {
                            data?: components["schemas"]["Category"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 新增分类（body 含 `scope`/`deptId`，ADR-015） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryReq"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 改分类 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryReq"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        post?: never;
        /** 删分类 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 我的自定义栏 */
        get: {
            parameters: {
                query?: {
                    userId?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResult"] & {
                            data?: components["schemas"]["Menu"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 新增栏 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MenuReq"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 改栏 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MenuReq"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        post?: never;
        /** 删栏 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 添加任务到栏 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MenuItemReq"];
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menus/{id}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 从栏移除任务 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                    itemId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上传附件（multipart，`taskId` 可选） */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        file?: string;
                        /** Format: int64 */
                        taskId?: number | null;
                    };
                };
            };
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 下载附件（登录 + 任务访问权校验；按 id 访问，不暴露物理路径） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 文件流 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** 删除附件 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["Ok"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 预览（登录 + 任务访问权校验；后端按 id 代理，修 SSRF） */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 文件流 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/operates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 操作日志分页（ADMIN / AUDITOR） */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResult"] & {
                            data?: components["schemas"]["OperateLogPage"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/logins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 登录日志分页（ADMIN / AUDITOR） */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResult"] & {
                            data?: components["schemas"]["LoginLogPage"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResult: {
            /** @example 0 */
            code: number;
            /** @example ok */
            message: string;
            data?: unknown;
            traceId?: string | null;
        };
        TokenVO: {
            accessToken?: string;
            refreshToken?: string;
            mustChangePassword?: boolean;
        };
        /** @enum {string} */
        Scope: "day" | "week" | "assigned" | "joined" | "collect" | "all";
        /**
         * @description 任务优先级（4 值，与 01 §8.1 / 02 DDL 对齐）。
         * @enum {string}
         */
        Priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
        /** @enum {string} */
        TaskStatus: "ACTIVE" | "DISABLED" | "ARCHIVED";
        /** @description 六大视图计数。**键名映射旧系统**：`joined`=旧 `join`、`assigned`=旧 `do`（0304/S5）；其余同。 */
        CountVO: {
            day?: number;
            week?: number;
            joined?: number;
            assigned?: number;
            collect?: number;
            all?: number;
        };
        /** @description 周期规则（TEXT 存 JSON，计算式展开；02 §4.3） */
        CycleRule: {
            /** @enum {string} */
            freq: "DAILY" | "WEEKLY" | "MONTHLY";
            /** @default 1 */
            interval: number;
            /** Format: date-time */
            dtstart: string;
            /** @description 仅 WEEKLY 生效 */
            byDay?: ("MO" | "TU" | "WE" | "TH" | "FR" | "SA" | "SU")[] | null;
            /** @description 与 until 互斥 */
            count?: number | null;
            /**
             * Format: date
             * @description 最后发生日期（含）；与 count 互斥。日期粒度（截至该日当地时区）
             */
            until?: string | null;
            /** @default Asia/Shanghai */
            tz: string;
        };
        UserBrief: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        UserVO: components["schemas"]["UserBrief"] & {
            username?: string;
            /** @description 手机号；ADMIN/USER_MANAGER 取得明文（用于编辑），其余角色脱敏 138****0000 */
            mobile?: string;
            /** @description 邮箱 */
            email?: string;
            /** Format: int64 */
            deptId?: number;
            deptName?: string;
            /** @enum {string} */
            roleCode?: "ADMIN" | "AUDITOR" | "USER_MANAGER" | "COMMON";
        };
        TagVO: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        CategoryBrief: {
            /** Format: int64 */
            id?: number;
            name?: string;
        };
        FileVO: {
            /** Format: int64 */
            id?: number;
            fileName?: string;
            /** Format: int64 */
            size?: number;
        };
        TaskVO: {
            /** Format: int64 */
            id?: number;
            title?: string;
            content?: string;
            status?: components["schemas"]["TaskStatus"];
            completed?: boolean;
            /** Format: date-time */
            dueAt?: string | null;
            /** Format: date-time */
            remindAt?: string | null;
            priority?: components["schemas"]["Priority"];
            cycleRule?: components["schemas"]["CycleRule"] | null;
            /** Format: date-time */
            cycleLastCompleted?: string | null;
            owner?: components["schemas"]["UserBrief"];
            assignees?: components["schemas"]["UserBrief"][];
            ccUsers?: components["schemas"]["UserBrief"][];
            participantIds?: number[];
            /**
             * Format: int64
             * @description 乐观锁版本号（更新须回传；失配 code=10006，ADR-013）
             */
            version?: number;
            category?: components["schemas"]["CategoryBrief"] | null;
            tags?: components["schemas"]["TagVO"][];
            subtaskCompleted?: number;
            subtaskTotal?: number;
            files?: components["schemas"]["FileVO"][];
            /** Format: date-time */
            createdAt?: string;
        };
        TaskDetailVO: components["schemas"]["TaskVO"] & {
            subtasks?: components["schemas"]["TaskVO"][];
        };
        TaskCreateReq: {
            title: string;
            content?: string;
            /**
             * Format: int64
             * @description 更新（PUT）时必填乐观锁版本；新建省略（ADR-013）
             */
            version?: number;
            /** Format: date-time */
            dueAt?: string | null;
            /** Format: date-time */
            remindAt?: string | null;
            priority?: components["schemas"]["Priority"];
            cycleRule?: components["schemas"]["CycleRule"] | null;
            /** Format: int64 */
            categoryId?: number | null;
            assigneeIds?: number[];
            ccIds?: number[];
            tagIds?: number[];
            fileIds?: number[];
        };
        TaskListData: {
            list?: components["schemas"]["TaskVO"][];
            total?: number;
            page?: number;
            size?: number;
        };
        TaskBrief: {
            /** Format: int64 */
            id?: number;
            title?: string;
            completed?: boolean;
            /** Format: date-time */
            dueAt?: string | null;
            priority?: components["schemas"]["Priority"];
        };
        /** @description 分类树节点（GET /categories 返回，嵌套 children） */
        Category: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** Format: int64 */
            parentId?: number | null;
            /**
             * @description 共享范围（ADR-015）
             * @enum {string}
             */
            scope?: "PERSONAL" | "DEPARTMENT" | "ORG";
            /**
             * Format: int64
             * @description DEPARTMENT 范围所属部门
             */
            deptId?: number | null;
            /**
             * Format: int64
             * @description 创建者
             */
            ownerId?: number;
            /** @description 同级排序（升序） */
            sort?: number;
            /** @description 该分类下任务数（含子分类） */
            taskCount?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            children?: components["schemas"]["Category"][];
        };
        /** @description 自定义栏条目（引用任务） */
        MenuItem: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            menuId?: number;
            /** Format: int64 */
            taskId?: number;
            sort?: number;
            /** @description 冗余任务摘要，供栏内直接渲染 */
            task?: components["schemas"]["TaskBrief"];
        };
        /** @description 自定义栏（GET /menus 返回，含条目） */
        Menu: {
            /** Format: int64 */
            id?: number;
            /**
             * Format: int64
             * @description 所属用户（菜单私有）
             */
            userId?: number;
            name?: string;
            sort?: number;
            /** Format: date-time */
            createdAt?: string;
            items?: components["schemas"]["MenuItem"][];
        };
        /** @description 部门树节点（GET /departments 返回，嵌套 children） */
        Department: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** Format: int64 */
            parentId?: number | null;
            /**
             * Format: int64
             * @description 部门负责人用户 id（组织级可见性，ADR-012）
             */
            leaderId?: number | null;
            sort?: number;
            /** @description 系统默认顶级部门：可改名，不可删除 */
            system?: boolean;
            children?: components["schemas"]["Department"][];
        };
        /** @description 操作日志（ADMIN / AUDITOR）。字段对应 `02 §6.2` 表 `audit_operate_log`（module/action/uri/method/user_id/ip/user_agent/duration/status/msg）。 */
        OperateLogVO: {
            /** Format: int64 */
            id?: number;
            /** @description 业务模块（如 task/identity/org/file/audit） */
            module?: string;
            /** @description 操作（如 complete/delete） */
            action?: string;
            /** @description 请求路径（对应表 uri） */
            uri?: string;
            /** @description HTTP 方法 */
            method?: string;
            /**
             * Format: int64
             * @description 操作人（对应表 user_id）
             */
            userId?: number;
            username?: string;
            ip?: string;
            /** @description 对应表 user_agent */
            userAgent?: string;
            /**
             * Format: int64
             * @description 耗时 ms（对应表 duration）
             */
            duration?: number;
            /**
             * @description 结果：SUCCESS 成功 / FAILURE 失败（应用层由表 status 0/1 映射，1 成功 0 失败）
             * @enum {string}
             */
            status?: "SUCCESS" | "FAILURE";
            /** @description 结果信息/异常摘要（对应表 msg） */
            msg?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description 登录日志（ADMIN / AUDITOR）。字段对应 `02 §6.2` 表 `audit_login_log`（success/ip/user_agent）。 */
        LoginLogVO: {
            /** Format: int64 */
            id?: number;
            username?: string;
            /** @description 是否成功（对应表 success；1 成功 0 失败） */
            success?: boolean;
            ip?: string;
            /** @description 对应表 user_agent */
            userAgent?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        OperateLogPage: {
            list?: components["schemas"]["OperateLogVO"][];
            total?: number;
            page?: number;
            size?: number;
        };
        LoginLogPage: {
            list?: components["schemas"]["LoginLogVO"][];
            total?: number;
            page?: number;
            size?: number;
        };
        /** @description 组织同步状态（orgsync） */
        SyncStatus: {
            running?: boolean;
            /** Format: date-time */
            lastSyncAt?: string | null;
            lastResult?: string | null;
            /** @enum {string} */
            mode?: "NONE" | "SCIM" | "PULL" | "PUSH";
        };
        RefreshReq: {
            refreshToken: string;
        };
        UserCreateReq: {
            username: string;
            name: string;
            /**
             * Format: password
             * @description 可选；首登 must_change_password 强制改密
             */
            password?: string | null;
            /**
             * Format: int64
             * @description 必填：新用户必须归属一个部门
             */
            deptId: number;
            /** @enum {string} */
            roleCode?: "ADMIN" | "AUDITOR" | "USER_MANAGER" | "COMMON";
            /** @description 手机号 */
            mobile?: string | null;
            /** @description 邮箱 */
            email?: string | null;
        };
        UserUpdateReq: {
            name?: string;
            /** Format: int64 */
            deptId?: number | null;
            /** @enum {string} */
            roleCode?: "ADMIN" | "AUDITOR" | "USER_MANAGER" | "COMMON";
            /** @enum {string} */
            status?: "ACTIVE" | "DISABLED";
            /** @description 手机号（传空串清空） */
            mobile?: string | null;
            /** @description 邮箱（传空串清空） */
            email?: string | null;
        };
        PasswordUpdateReq: {
            /**
             * Format: password
             * @description 非首登须提供
             */
            oldPassword?: string | null;
            /** Format: password */
            newPassword: string;
        };
        DeptCreateReq: {
            name: string;
            /** Format: int64 */
            parentId?: number | null;
            /** Format: int64 */
            leaderId?: number | null;
        };
        DeptUpdateReq: {
            name?: string;
            /** Format: int64 */
            parentId?: number | null;
            /** Format: int64 */
            leaderId?: number | null;
        };
        CategoryReq: {
            name: string;
            /** Format: int64 */
            parentId?: number | null;
            /**
             * @default PERSONAL
             * @enum {string}
             */
            scope: "PERSONAL" | "DEPARTMENT" | "ORG";
            /**
             * Format: int64
             * @description scope=DEPARTMENT 时必填
             */
            deptId?: number | null;
        };
        TagReq: {
            name: string;
        };
        MenuReq: {
            name: string;
            sort?: number;
        };
        MenuItemReq: {
            /** Format: int64 */
            taskId: number;
        };
        /** @description 更新任务（在 TaskCreateReq 基础上 `version` 必填，ADR-013） */
        TaskUpdateReq: components["schemas"]["TaskCreateReq"] & {
            /** Format: int64 */
            version: number;
        };
        /** @description 完成/取消完成请求体（ADR-013：更新须携带 `version`；周期任务需带 `dueAt` 指定实例，见 02 §4.3 R2） */
        TaskCompleteReq: {
            /**
             * Format: int64
             * @description 乐观锁版本号（失配 code=10006）
             */
            version: number;
            /**
             * Format: date-time
             * @description 周期任务指定实例时间；非周期可空
             */
            dueAt?: string | null;
        };
        /** @description 私有 IDM 组织推送报文（规范通用形态；厂商私有格式由 OrgPushAdapter 映射） */
        OrgPushPayload: {
            /**
             * @description 全量/增量
             * @default INCREMENTAL
             * @enum {string}
             */
            type: "FULL" | "INCREMENTAL";
            /** Format: date-time */
            timestamp?: string | null;
            departments: components["schemas"]["OrgPushDept"][];
            users: components["schemas"]["OrgPushUser"][];
            /** @description 需失效（置 DISABLED）的外部 id 列表 */
            deleted?: {
                userExternalIds?: string[];
                deptExternalIds?: string[];
            };
        };
        OrgPushDept: {
            /** @description 外部源部门 id（幂等映射键） */
            externalId: string;
            name: string;
            parentExternalId?: string | null;
            /** @description 负责人外部用户 id */
            leaderExternalId?: string | null;
            sort?: number | null;
        };
        OrgPushUser: {
            /** @description 外部源用户 id（幂等映射键） */
            externalId: string;
            username?: string | null;
            name?: string | null;
            mobile?: string | null;
            email?: string | null;
            primaryDeptExternalId?: string | null;
            deptExternalIds?: string[];
            /**
             * @default ACTIVE
             * @enum {string}
             */
            status: "ACTIVE" | "DISABLED";
        };
        /** @description SCIM 资源（标准 schema；字段随 IDP 而异，映射见 02 §3.3） */
        ScimResource: {
            [key: string]: unknown;
        };
        ScimPatchOp: {
            schemas?: string[];
            Operations: {
                /** @enum {string} */
                op: "add" | "remove" | "replace";
                path?: string | null;
                value?: unknown;
            }[];
        };
    };
    responses: {
        /** @description OK */
        Ok: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResult"];
            };
        };
        /** @description Token pair */
        Token: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResult"] & {
                    data?: components["schemas"]["TokenVO"];
                };
            };
        };
        /** @description 任务列表 */
        TaskList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResult"] & {
                    data?: components["schemas"]["TaskListData"];
                };
            };
        };
        /** @description 任务分页 */
        TaskPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResult"] & {
                    data?: components["schemas"]["TaskListData"];
                };
            };
        };
        /** @description 用户分页 */
        UserPage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiResult"] & {
                    data?: {
                        list?: components["schemas"]["UserVO"][];
                        total?: number;
                    };
                };
            };
        };
    };
    parameters: {
        Id: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
